(function(t){function l(h){if(b[h])return b[h].exports;var e=b[h]={exports:{},id:h,loaded:!1};t[h].call(e.exports,e,e.exports,l);e.loaded=!0;return e.exports}var b={};l.m=t;l.c=b;l.p="";return l(0)})([function(t,l){(function(){if(!document.getElementById("mouseposition-extension-element-coordinate-display")){var b=function(a,b){for(var d in b)b.hasOwnProperty(d)&&(a.style[d]=b[d])},h=!0,e=!1,l=!0,t=!1,u=!1,B=!1,y=!0;var f=document.createElement("pre");f.id="mouseposition-extension-element-coordinate-display";
var v=document.createElement("div");v.id="mouseposition-extension-element-full-container";b(v,{position:"fixed",top:"0px",left:"0px",right:"0px",bottom:"0px",pointerEvents:"none",zIndex:"2147483647",fontFamily:'"Helvetica Neue", Helvetica, Arial, sans-serif;',fontWeight:"400"});document.body.appendChild(v);var n=document.createElement("div"),m=document.createElement("pre");v.appendChild(n);n.appendChild(m);b(m,{flex:"1",textAlign:"center",backgroundColor:"rgba(255,255,255,0.7)",color:"#000",minWidth:"42px",
minHeight:"12px",transition:"all 1s"});n.id="mouseposition-extension-element-rect-display";b(n,{display:"none"});var w=0,x=0,z=null;v.appendChild(f);b(f,{position:"absolute",display:"none",background:"#fff",fontSize:"12px",lineHeight:"14px",borderRadius:"3px",borderWidth:"1px",borderColor:"black",borderTopColor:"#222",borderBottomColor:"#333",borderStyle:"solid",padding:"3px",zIndex:"2147483647",color:"#222",userSelect:"none",cursor:"default","font-family":'"Helvetica Neue", Helvetica, Arial, sans-serif'});
b(n,{position:"absolute",background:"rgba(255,255,255,0.7)",outline:"black 1px solid",fontSize:"12px",zIndex:"2147483647",justifyContent:"center",alignItems:"center",userSelect:"none",cursor:"default",color:"#000","font-family":'"Helvetica Neue", Helvetica, Arial, sans-serif'});var E=function(a){u?f&&(f.style.display="block"):f&&(f.style.display="none")};chrome.runtime.onMessage.addListener(function(a){"switch"===a.op&&(u=a.value);E(u);"options"===a.op&&C(a.value)});var F=null,G=function(a){if(u&&
(a=a||F)){F=a;var d=a.clientX,r=a.clientY,g=a.pageX,q=a.pageY,p=20,k=10,c=[a.clientX+", "+a.clientY];e&&(c[0]+=" (page)");z=a;if(d!==g||r!==q)c=[g+", "+q],e&&(c[0]+=" (page)"),c.push(a.clientX+", "+a.clientY),c[c.length-1]=e?c[c.length-1]+" (client)":"("+c[c.length-1]+")";t&&(c.push(a.screenX+", "+a.screenY),c[c.length-1]=e?c[c.length-1]+" (screen)\n":"["+c[c.length-1]+"]");f.textContent=c.join(e?"\n":" ");g=f.getBoundingClientRect();a=g.width;g=g.height;r+p+g>window.innerHeight&&(p=-g);d+k+a>window.innerWidth&&
(k=-1*k-a);b(f,{left:d+k+"px",top:r+p+"px",color:"#222",display:l?"block":"none"});l||h||(b(f,{display:"block",color:"red"}),f.textContent="Coordinates Extension configured so it doesnt display anything.\n\rCheck extension options.");B&&(p=d-w,k=r-x,a=w,g=x,d<w&&(a=d,p=w-d),r<x&&(g=r,k=x-r),m.textContent=p+"x"+k,d=m.getBoundingClientRect(),p<d.width&&32>p||k<d.height&&14>k?(g<k+d.height?b(m,{position:"relative",left:"17px",top:"0px"}):b(m,{position:"relative",top:"-16px",left:"-3px"}),a>window.innerHeight-
42?b(m,{position:"relative",left:"-42px",top:"0px"}):b(m,{position:"relative",left:"0px"}),b(m,{backgroundColor:"rgba(255,255,255,0.9)"}),b(n,{display:"block"})):(b(n,{display:"flex"}),b(m,{top:"0px",left:"0px",backgroundColor:"transparent"})),b(n,{width:p+"px",height:k+"px",left:a+"px",top:g+"px",fontSize:"12px"}))}},D=!1,A=function(a){D||(D=!0,h&&(a&&16===a.keyCode||y)&&(B=!0,z&&(w=z.clientX,x=z.clientY)))},q=function(a,d){D=!1;if(a&&16===a.keyCode||y||d)B=!1,b(n,{display:"none",width:"0px",height:"0px"})},
C=function(a){h=a.measureArea;e=a.longFormat;l=a.displayMousePosition;document.removeEventListener("keydown",A);document.removeEventListener("mousedown",A);document.removeEventListener("mouseup",q);document.removeEventListener("keyup",q);h=a.measureArea;t=a.doScreenCoordinates;h?("MOUSE"===a.trigger&&(y=!0,document.addEventListener("mousedown",A),document.addEventListener("mouseup",q)),"KEYBOARD"===a.trigger&&(y=!1,document.addEventListener("keydown",A),document.addEventListener("keyup",q))):q(null,
!0);G()};q(null,!0);document.addEventListener("mousemove",G,!0);window.mousepositionOptionsPage&&(window.mousepositionOptionsPage.pubsub.sub("optionsChanged",C),window.mousepositionOptionsPage.optionsPromise.then(function(a){C(a)}),u=!0,E(u))}})()}]);
