var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,e){a!=Array.prototype&&a!=Object.prototype&&(a[d]=e.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";
$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};$jscomp.symbolCounter_=0;$jscomp.Symbol=function(a){return $jscomp.SYMBOL_PREFIX+(a||"")+$jscomp.symbolCounter_++};
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.arrayIterator(this)}});$jscomp.initSymbolIterator=function(){}};$jscomp.arrayIterator=function(a){var d=0;return $jscomp.iteratorPrototype(function(){return d<a.length?{done:!1,value:a[d++]}:{done:!0}})};
$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};$jscomp.makeIterator=function(a){$jscomp.initSymbolIterator();var d=a[Symbol.iterator];return d?d.call(a):$jscomp.arrayIterator(a)};
$jscomp.polyfill=function(a,d,e,f){if(d){e=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var b=a[f];b in e||(e[b]={});e=e[b]}a=a[a.length-1];f=e[a];d=d(f);d!=f&&null!=d&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:d})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(a){function d(){this.batch_=null}function e(c){return c instanceof b?c:new b(function(a,b){a(c)})}if(a&&!$jscomp.FORCE_POLYFILL_PROMISE)return a;d.prototype.asyncExecute=function(c){null==this.batch_&&(this.batch_=[],this.asyncExecuteBatch_());this.batch_.push(c);return this};d.prototype.asyncExecuteBatch_=function(){var c=this;this.asyncExecuteFunction(function(){c.executeBatch_()})};var f=$jscomp.global.setTimeout;d.prototype.asyncExecuteFunction=function(c){f(c,
0)};d.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var c=this.batch_;this.batch_=[];for(var a=0;a<c.length;++a){var b=c[a];delete c[a];try{b()}catch(h){this.asyncThrow_(h)}}}this.batch_=null};d.prototype.asyncThrow_=function(c){this.asyncExecuteFunction(function(){throw c;})};var b=function(c){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var a=this.createResolveAndReject_();try{c(a.resolve,a.reject)}catch(k){a.reject(k)}};b.prototype.createResolveAndReject_=
function(){function c(c){return function(l){b||(b=!0,c.call(a,l))}}var a=this,b=!1;return{resolve:c(this.resolveTo_),reject:c(this.reject_)}};b.prototype.resolveTo_=function(c){if(c===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(c instanceof b)this.settleSameAsPromise_(c);else{a:switch(typeof c){case "object":var a=null!=c;break a;case "function":a=!0;break a;default:a=!1}a?this.resolveToNonPromiseObj_(c):this.fulfill_(c)}};b.prototype.resolveToNonPromiseObj_=function(c){var a=
void 0;try{a=c.then}catch(k){this.reject_(k);return}"function"==typeof a?this.settleSameAsThenable_(a,c):this.fulfill_(c)};b.prototype.reject_=function(a){this.settle_(2,a)};b.prototype.fulfill_=function(a){this.settle_(1,a)};b.prototype.settle_=function(a,b){if(0!=this.state_)throw Error("Cannot settle("+a+", "+b|"): Promise already settled in state"+this.state_);this.state_=a;this.result_=b;this.executeOnSettledCallbacks_()};b.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var a=
this.onSettledCallbacks_,b=0;b<a.length;++b)a[b].call(),a[b]=null;this.onSettledCallbacks_=null}};var g=new d;b.prototype.settleSameAsPromise_=function(a){var b=this.createResolveAndReject_();a.callWhenSettled_(b.resolve,b.reject)};b.prototype.settleSameAsThenable_=function(a,b){var c=this.createResolveAndReject_();try{a.call(b,c.resolve,c.reject)}catch(h){c.reject(h)}};b.prototype.then=function(a,d){function c(a,b){return"function"==typeof a?function(b){try{e(a(b))}catch(r){f(r)}}:b}var e,f,l=new b(function(a,
b){e=a;f=b});this.callWhenSettled_(c(a,e),c(d,f));return l};b.prototype.catch=function(a){return this.then(void 0,a)};b.prototype.callWhenSettled_=function(a,b){function c(){switch(e.state_){case 1:a(e.result_);break;case 2:b(e.result_);break;default:throw Error("Unexpected state: "+e.state_);}}var e=this;null==this.onSettledCallbacks_?g.asyncExecute(c):this.onSettledCallbacks_.push(function(){g.asyncExecute(c)})};b.resolve=e;b.reject=function(a){return new b(function(b,c){c(a)})};b.race=function(a){return new b(function(b,
c){for(var d=$jscomp.makeIterator(a),f=d.next();!f.done;f=d.next())e(f.value).callWhenSettled_(b,c)})};b.all=function(a){var c=$jscomp.makeIterator(a),d=c.next();return d.done?e([]):new b(function(a,b){function f(b){return function(c){g[b]=c;m--;0==m&&a(g)}}var g=[],m=0;do g.push(void 0),m++,e(d.value).callWhenSettled_(f(g.length-1),b),d=c.next();while(!d.done)})};return b},"es6-impl","es3");
(function(a){function d(f){if(e[f])return e[f].exports;var b=e[f]={exports:{},id:f,loaded:!1};a[f].call(b.exports,b,b.exports,d);b.loaded=!0;return b.exports}var e={};d.m=a;d.c=e;d.p="";return d(0)})([function(a,d,e){function f(a){chrome.tabs.query({},function(b){var c;for(c=0;c<b.length;c+=1)chrome.tabs.sendMessage(b[c].id,{op:"options",value:a})})}function b(a){chrome.storage.sync.set(a,function(){var b=document.getElementById("status");b.textContent="Options saved.";f(a);k.pub("optionsChanged",
a);setTimeout(function(){b.textContent=""},750)})}function g(){var a={},b=document.getElementById("trigger-keyboard").checked,c=document.getElementById("trigger-mouse").checked;b&&(a.trigger=h.KEYBOARD);c&&(a.trigger=h.MOUSE);a.doScreenCoordinates=document.getElementById("screen-coordinates").checked;a.measureArea=!!document.getElementById("measure-area").checked;a.longFormat=!!document.getElementById("long-format").checked;a.displayMousePosition=!!document.getElementById("display-mouse-position").checked;
return a}function c(){chrome.storage.sync.get(n,function(a){function b(a,b){document.getElementById(a).checked=b}a.trigger===h.MOUSE&&b("trigger-mouse",!0);a.trigger===h.KEYBOARD&&b("trigger-keyboard",!0);b("screen-coordinates",a.doScreenCoordinates);b("measure-area",a.measureArea);b("long-format",a.longFormat);b("display-mouse-position",a.displayMousePosition);q();p();l.resolver(a)})}a=e(1);var l=new (e(2)),k=new a,h={MOUSE:"MOUSE",KEYBOARD:"KEYBOARD"},n={longFormat:!1,displayMousePosition:!0,trigger:h.MOUSE,
measureArea:!0,doScreenCoordinates:!1},q=function(){var a=document.getElementById("measure-area"),b=document.getElementById("trigger-keyboard"),c=document.getElementById("trigger-mouse");a.checked?(b.removeAttribute("disabled",a.checked),c.removeAttribute("disabled",a.checked),document.querySelectorAll(".triggers-labels").forEach(function(a){a.classList.remove("disabled")})):(b.setAttribute("disabled",a.checked),c.setAttribute("disabled",a.checked),document.querySelectorAll(".triggers-labels").forEach(function(a){a.classList.add("disabled")}))},
p=function(){var a=document.getElementById("display-mouse-position"),b=[document.getElementById("long-format"),document.getElementById("screen-coordinates")];a.checked?(b.forEach(function(b){b.removeAttribute("disabled",a.checked)}),document.querySelectorAll(".mouse-postion-label").forEach(function(a){a.classList.remove("disabled")})):(b.forEach(function(b){b.setAttribute("disabled",a.checked)}),document.querySelectorAll(".mouse-postion-label").forEach(function(a){a.classList.add("disabled")}))};
document.addEventListener("DOMContentLoaded",function(){c();var a=document.querySelectorAll("input, select"),b;for(b=0;b<a.length;b+=1)a[b].addEventListener("change",function(){document.getElementById("save").classList.add("dirty");k.pub("optionsChanged",g())});document.getElementById("measure-area").addEventListener("change",function(){q()});document.getElementById("display-mouse-position").addEventListener("change",function(){p()})});document.getElementById("save").addEventListener("click",function(){document.getElementById("save").classList.remove("dirty");
b(g())});document.getElementById("reset").addEventListener("click",function(){b(n);c()});window.mousepositionOptionsPage={pubsub:k,optionsPromise:l}},function(a,d){a.exports=function(){var a={};this.sub=function(d,b){a[d]=a[d]||[];a[d].push(b)};this.pub=function(d,b){var e=Array.prototype.slice.apply(arguments);e.splice(0,1);a[d].forEach(function(a){a.apply(null,e)})}}},function(a,d){a.exports=function(){var a,d,b=new Promise(function(b,c){a=b;d=c});b.resolver=a;b.rejecter=d;return b}}]);
